# @Author: Guan Gui <guiguan>
# @Date:   2018-01-25T18:14:56+11:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2018-01-25T18:52:00+11:00

os: linux
dist: trusty
sudo: false
language: node_js
# Node version specified in .nvmrc
node_js: null

git:
  depth: 3
  submodules: false

script:
  - set -e
  - yarn install --no-progress
  - yarn flow && yarn run eslint --rule 'import/no-unresolved:off'

notifications:
  slack:
    rooms:
      - secure: L0dMIw5ogSQyk3VRKJtPoAae3+5DIFg+LTifji4kbUQVtkHI7YFu+0HHnshQBZ0qh6Tol1L4zjF6fLsemFhCqU+u4RREdmkObX8TvKYmsjqr//rR2FPkJuENxGB2/tsjzojFgTkcJJ8BeLgrfA11l98YShXs9HS4vb7Br5qEk44QQnZjY+cHiH+xdOK+oYuYDdR2/QLFMMQdZoxl0qrgY8dIoPCX3obdvMZ0T0f5LOLOQaho+bwoQKcTGMYTk9UrJ0gBZ4VqaScdMHc8r+MkeGs+AT+ZkqBl7I4QxOEJlRLVuSZTuP+jUbrvkKEmUjfqBLQSH0JMY1C4c1U/x5PdRvEYCe4/N2ZYe7uAfXEm2HZ6m33CKhB90gDBQmKv05JJrqBeLwpB3+LECIiriFOwRPfiFtg90fhR7+tpJ7/2OXtIxpgkQGPgE72/sWEoYVyAAlQ17U6gZtvg9+UprNa2RhbTx8AkmJvOLN6zPMgnU1FtqCpoT4gyHurdFxiiStmr2RTfl4W1JCOK+H+8iT6Bwy3+H1pkr7XTSFZpVoqHyv6put+COJW61JzPFN/inx8zr52rmMjjTavctkn7ibor8m/P2bK/gD5/tzbPoOPj+NKYa6+ovcqA0qrV8ngiaNynx3NO0JwKlfGvKZmrI2XJjdP0MMbSmQcVbgXSb6empHI=
    template:
      - 'Code quality and unit testing for build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of <https://github.com/%{repository_slug}/tree/%{branch}|%{repository_slug}@%{branch}> by %{author} %{result} in %{duration}: %{commit_message}'
